[package]
name = "relay_client"
version = "0.1.0"
edition = "2021"

[features]
default = ["tokio-tungstenite/native-tls"]
rustls = ["tokio-tungstenite/rustls-tls-native-roots"]

[dependencies]
relay_rpc = { path = "../relay_rpc" }
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
thiserror = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_qs = "0.10"
pin-project = "1.0"
chrono = { version = "0.4", default-features = false, features = ["alloc", "std"] }
url = "2.3"
http = "0.2"

# HTTP client dependencies.
reqwest = { version = "0.11", features = ["json"] }

# WebSocket client dependencies.
tokio = { version = "1.22", features = ["rt", "time", "sync", "macros", "rt-multi-thread"] }
tokio-tungstenite = { version = "0.18" }
futures-channel = { version = "0.3" }
tokio-stream = { version = "0.1" }
tokio-util = { version = "0.7" }
